//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livraria.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResLabel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResLabel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Livraria.Web.App_GlobalResources.ResLabel", typeof(ResLabel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        public static string btnAcoes {
            get {
                return ResourceManager.GetString("btnAcoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        public static string btnAdicionar {
            get {
                return ResourceManager.GetString("btnAdicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        public static string btnFechar {
            get {
                return ResourceManager.GetString("btnFechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string btnSalvar {
            get {
                return ResourceManager.GetString("btnSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguarde o término do processamento da requisição!.
        /// </summary>
        public static string lblAguardeProcessamento {
            get {
                return ResourceManager.GetString("lblAguardeProcessamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        public static string lblAno {
            get {
                return ResourceManager.GetString("lblAno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        public static string lblAutor {
            get {
                return ResourceManager.GetString("lblAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autores.
        /// </summary>
        public static string lblAutores {
            get {
                return ResourceManager.GetString("lblAutores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string lblDescricao {
            get {
                return ResourceManager.GetString("lblDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editora.
        /// </summary>
        public static string lblEditora {
            get {
                return ResourceManager.GetString("lblEditora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editoras.
        /// </summary>
        public static string lblEditoras {
            get {
                return ResourceManager.GetString("lblEditoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estoque.
        /// </summary>
        public static string lblEstoque {
            get {
                return ResourceManager.GetString("lblEstoque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gênero.
        /// </summary>
        public static string lblGenero {
            get {
                return ResourceManager.GetString("lblGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gêneros.
        /// </summary>
        public static string lblGeneros {
            get {
                return ResourceManager.GetString("lblGeneros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livro.
        /// </summary>
        public static string lblLivro {
            get {
                return ResourceManager.GetString("lblLivro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livros.
        /// </summary>
        public static string lblLivros {
            get {
                return ResourceManager.GetString("lblLivros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string lblNome {
            get {
                return ResourceManager.GetString("lblNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Páginas.
        /// </summary>
        public static string lblPaginas {
            get {
                return ResourceManager.GetString("lblPaginas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string lblValor {
            get {
                return ResourceManager.GetString("lblValor", resourceCulture);
            }
        }
    }
}
